packages:
  - packages/**
  - tests/**
  - '!**/dist/**'
  - '!packages/plugins/autoupdate'
onlyBuiltDependencies:
  - '@commoners/testing'
  - electron
  - esbuild
  - ffi-napi
  - ref-napi
  - sharp
