packages:
  - packages/**
  - examples/**
  - '!**/dist/**'
  - '!packages/plugins/autoupdate'
  - '!packages/create-commoners/template'
onlyBuiltDependencies:
  - '@commoners/testing'
  - electron
  - esbuild
  - sharp
