name: Back-end Tests
on:
  schedule:
    - cron: "0 16 * * *"  # Daily at noon EST
  pull_request:

concurrency:  # Cancel previous workflows on the same pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_NUMBER: 2  # increase to reset cache manually

jobs:
  testing:
    name: Back-end tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags

      - name: Set cache date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Commoners
        run: npm ci 

      - name: Build Commoners
        run: npm run build

      - name: Run tests
        run: npm run coverage
